#+TITLE: A paper written in Org.
* A headline
  :PROPERTIES:
  :ID:       6c4f64c4-4e81-4852-b324-e36572201dcd
  :END:
Aliquam erat volutpat.  Nunc eleifend leo vitae magna.  In id erat non orci commodo lobortis.  Proin neque massa, cursus ut, gravida ut, lobortis eget, lacus.  Sed diam.  Praesent fermentum tempor tellus.  Nullam tempus.  Mauris ac felis vel velit tristique imperdiet.  Donec at pede.  Etiam vel neque nec dui dignissim bibendum.  Vivamus id enim.  Phasellus neque orci, porta a, aliquet quis, semper a, massa.  Phasellus purus.  Pellentesque tristique imperdiet tortor.  Nam euismod tellus id erat.

#+NAME: code_kdeplot
#+begin_src python :results file :exports results 
import os
import matplotlib.pyplot as plt
from scipy.stats import norm
import seaborn as sns

filename = 'kde.pdf'
filepath = os.path.join(os.getcwd(), 'Figures', filename)
figsize = 6, 4

_, ax = plt.subplots(figsize=figsize)
y = norm.rvs(size=1000)
sns.kdeplot(data=y, ax=ax)
sns.despine()
plt.tight_layout()
plt.savefig(filepath, transparent=True)
return filepath
#+end_src
#+NAME: fig_kde
#+CAPTION[KDE plot]: Kernel Density Estimate.
#+RESULTS: code_kdeplot
[[file:/home/frederik/MultiPaper/PaperA/Figures/kde.pdf]]

- Nam euismod tellus id erat.
- Pellentesque dapibus suscipit ligula.
- Nullam eu ante vel est convallis dignissim.

Proin quam nisl, tincidunt et, mattis eget, convallis nec, purus.  Quam [[ref:fig_kde][ref:fig_kde]].
* Another headline

Quam [[id:6c4f64c4-4e81-4852-b324-e36572201dcd][A headline]].
